# Units used in the field of chemistry

[units.derived.angstrom]
symbol = "Å"
name = "angstrom"
value.number = 1e-10
value.unit = "m"
alt_names = [ "ångström" ]
canon_symbol = true

[units.compound.reciprocal_centimetre]
components = [["centimetre", -1]]
name = "reciprocal_centimetre"
alt_names = [ "reciprocal_centimeter", "inverse_centimetre", "inverse_centimeter", "wavenumber" ]
add_to_namespace = true
