"""United States customary units."""

# Length
[units.derived.mil]
# Identical to imperial.thou but different name
name = "mil"
value.number = "0.0000254"
value.unit = "m"

[units.derived.rod]
symbol = "rd"
name = "rod"
value.number = "5.0292"
value.unit = "m"
alt_names = [ "pole", "perch" ]

# US survey units - like the normal imperial/US length units but defined using the US survey foot
# Use NIST's 2023 approximations
[units.derived.us_survey_inch]
# Not provided by NIST but definition is 1/39.37 m, so provide to 12 sigfigs
symbol = "in"
name = "us_survey_inch"
value.number = "0.0254000508001"
value.unit = "m"    

[units.derived.us_survey_link]
symbol = "li"
name = "us_survey_link"
value.number = "0.201168402"
value.unit = "m"

[units.derived.us_survey_foot]
symbol = "ft"
name = "us_survey_foot"
value.number = "0.304800609601"
value.unit = "m"

[units.derived.us_survey_fathom]
symbol = "ftm"
name = "us_survey_fathom"
value.number = "1.828803658"
value.unit = "m"

[units.derived.us_survey_rod]
symbol = "rd"
name = "us_survey_rod"
value.number = "5.029210058"
value.unit = "m"
alt_names = [ "us_survey_pole", "us_survey_perch" ]

[units.derived.us_survey_chain]
symbol = "ch"
name = "us_survey_chain"
value.number = "20.116840234"
value.unit = "m"

[units.derived.us_survey_furlong]
symbol = "fur"
name = "us_survey_furlong"
value.number = "201.168402337"
value.unit = "m"

[units.derived.us_survey_cable]
name = "us_survey_cable"
value.number = "219.456438913"
value.unit = "m"
alt_names = [ "us_survey_cables_length" ]

[units.derived.us_survey_mile]
symbol = "mi"
name = "us_survey_mile"
value.number = "1609.347218694"
value.unit = "m"
alt_names = [ "statute_mile" ]

[units.derived.us_survey_league]
symbol = "lea"
name = "us_survey_league"
value.number = "4828.041656083"
value.unit = "m"

[units.derived.us_survey_acre]
symbol = "ac"
name = "us_survey_acre"
value.number = "4046.872609874"
value.unit = "m**2"

[units.derived.us_survey_section]
name = "us_survey_section"
value.number = "2589998.47"
value.unit = "m**2"

# Capacity
[units.derived.cubic_inch]
symbol = "cu in"
name = "cubic_inch"
value.number = "1"
value.unit = "inch**3"

[units.derived.cubic_foot]
symbol = "cu ft"
name = "cubic_foot"
value.number = "1"
value.unit = "foot**3"

[units.derived.cubic_yard]
symbol = "cu yd"
name = "cubic_yard"
value.number = "1"
value.unit = "yard**3"

[units.derived.us_fluid_ounce]
symbol = "fl oz"
name = "us_fluid_ounce"
value.number = "0.0295735295625"
value.unit = "litre"

# Nautical units
[units.derived.us_fathom]
symbol = "ftm"
name = "us_fathom"
value.number = "1.8288"
value.unit = "m"

[units.derived.us_cable]
name = "us_cable"
value.number = "219.456"
value.unit = "m"
